baseURL = 'https://karlhaworth.com'
languageCode = 'en-us'
title = 'Karl Haworth'
theme = "karlhaworth-com"

disableKinds = ["taxonomy", "term"]

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5