baseURL = 'https://karlhaworth.com'
languageCode = 'en-us'
title = 'Karl Haworth'
theme = "karlhaworth-com"

disableKinds = ["taxonomy", "term"]

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[module]
[[module.mounts]]
  source = 'themes/karlhaworth-com/node_modules/lightbox2/dist'
  target = 'static/lightbox2'