baseURL = 'https://karlhaworth.com'
languageCode = 'en-us'
title = 'Karl Haworth'
theme = "karlhaworth-com"

enableRobotsTXT = true

disableKinds = ["taxonomy", "term"]

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[module]
  [[module.mounts]]
    source = 'themes/karlhaworth-com/node_modules/lightbox2/dist'
    target = 'assets/lightbox2'
  [[module.mounts]]
    source = 'themes/karlhaworth-com/node_modules/lightbox2/dist/images'
    target = 'static/images'
  [[module.mounts]]
    source = 'themes/karlhaworth-com/static'
    target = 'static'
  [[module.mounts]]
    source = 'themes/karlhaworth-com/assets'
    target = ''
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
