baseURL = 'https://karlhaworth.com'
languageCode = 'en-us'
title = 'Karl Haworth'
theme = "karlhaworth-com"

enableRobotsTXT = true

disableKinds = ["taxonomy", "term"]

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[module]
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'