# theme.toml template for a Hugo theme

name = "KarlHaworth.com"
license = "MIT"
licenselink = "https://github.com/karlhaworth/karlhaworth.com_hugo/blob/main/LICENSE"
description = "A theme for karlhaworth.com"
homepage = "https://karlhaworth.com/"
tags = []
features = []
min_version = "0.0.1"

[author]
  name = "Karl Haworth"
  homepage = "https://karlhaworth.com/"